# This is a basic workflow to help you get started with Actions

name: Distribute

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # Only run this workflow when a tag is pushed
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "distribute"
  distribute:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Windows SDK
      - name: Install Windows SDK
        uses: git-for-windows/setup-git-for-windows-sdk@v1
        with:
          cache: true

      # Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # init pdm
      - name: init pdm
        run: |
          pipx install pdm
          pdm install

      # Run the distribute script
      - name: Run the distribute script
        run: |
          pdm run python ./scripts/distribute.py -v ${{ github.ref }} --download_upx --p7zip

      - name: upload release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ env.FIRMWARE }}/build/release/*
          token: ${{ secrets.GITHUB_TOKEN }}